# Generated by Django 4.0.1 on 2022-02-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-id']},
        ),
    ]
