# Generated by Django 4.0.2 on 2022-02-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.ImageField(blank=True, upload_to='topics/'),
        ),
    ]
