# Generated by Django 4.0.1 on 2022-02-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_topic_options'),
        ('topics', '0003_topic_color_alter_topic_icon'),
    ]

    operations = [
    ]
