# Generated by Django 4.0.2 on 2022-02-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_topic_options'),
        ('snippets', '0002_alter_snippet_options_alter_snippetfile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=models.CharField(blank=True, default='', max_length=25000),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='snippets', to='topics.Topic'),
        ),
    ]
