# Generated by Django 4.0.2 on 2022-02-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_topic_options'),
        ('snippets', '0003_alter_snippet_description_alter_snippet_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=models.CharField(default='', max_length=25000),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='topics',
            field=models.ManyToManyField(related_name='snippets', to='topics.Topic'),
        ),
    ]
