# Generated by Django 4.0.1 on 2022-02-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_alter_comment_created_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SnippetFile',
            new_name='File',
        ),
    ]
